image: Visual Studio 2022
configuration: Release
branches:
  only:
    - master

build: off

# build config
build_script:
  - .\build.sh

# artifacts config
artifacts:
  - path: '.\build\bin\*.nupkg'

# publish artifacts config
deploy:
  - provider: NuGet
    api_key:
      secure: dbDJxjJFFo0JcJKoWKD2rb9V9Spc78gQs87N767mJ7T7LLNnnwfOEVqGpC2cFVhJ