image: Visual Studio 2019
configuration: Release
branches:
  only:
    - master

# build config
build_script:
  - .\build.sh

# artifacts config
artifacts:
  - path: '.\build\bin\*.nupkg'

# publish artifacts config
deploy:
  - provider: NuGet
    api_key:
      secure: +FtvpHdcRnhymyGhQT0j4fKmKzQiKsnnjmy4tTxzutvW3a307UgoSBJ7ASJLqmG3